# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0e1317"

# Main text color
theme[main_fg]="#f6cf9b"

# Title color for boxes
theme[title]="#cd98cd"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#a8cccc"

# Background color of selected item in processes box
theme[selected_bg]="#93a0ab"

# Foreground color of selected item in processes box
theme[selected_fg]="#f6cf9b"

# Color of inactive/disabled text
theme[inactive_fg]="#93a0ab"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#cd98cd"

# Box outline and divider line color
theme[cpu_box]="#78bf78"
theme[mem_box]="#78bf78"
theme[net_box]="#78bf78"
theme[proc_box]="#78bf78"
theme[div_line]="#93a0ab"

# Gradient for all meters and graphs
theme[temp_start]="#a8cccc"
theme[temp_mid]="#93b2c3"
theme[temp_end]="#78bf78"


theme[cpu_start]="#a8cccc"
theme[cpu_mid]="#93b2c3"
theme[cpu_end]="#78bf78"


theme[free_start]="#93b2c3"
theme[free_mid]="#bab38c"
theme[free_end]="#bab38c"


theme[cached_start]="#bab38c"
theme[cached_mid]="#bab38c"
theme[cached_end]="#bab38c"


theme[available_start]="#a8cccc"
theme[available_mid]="#a8cccc"
theme[available_end]="#a8cccc"


theme[used_start]="#78bf78"
theme[used_mid]="#78bf78"
theme[used_end]="#78bf78"


theme[download_start]="#bab38c"
theme[download_mid]="#a8cccc"
theme[download_end]="#93b2c3"


theme[upload_start]="#bab38c"
theme[upload_mid]="#a8cccc"
theme[upload_end]="#93b2c3"