# UI Colors (extended)
accent = "#93b2c3"
cursor = "#f6cf9b"

# Primary colors
foreground = "#f6cf9b"
background = "#0e1317"

# Selection colors
selection_foreground = "#0e1317"
selection_background = "#f6cf9b"

# Normal colors (ANSI 0-7)
color0 = "#0e1317"
color1 = "#a14a3a"
color2 = "#78bf78"
color3 = "#bab38c"
color4 = "#93b2c3"
color5 = "#cd98cd"
color6 = "#a8cccc"
color7 = "#f6cf9b"

# Bright colors (ANSI 8-15)
color8 = "#93a0ab"
color9 = "#ca6c5a"
color10 = "#b2deb2"
color11 = "#d9d5bd"
color12 = "#bfd3dd"
color13 = "#e3c0e3"
color14 = "#c8e0e0"
color15 = "#ffffff"
