# Background and foreground colors
background = #0e1317
foreground = #f6cf9b

# Standard colors
palette = 0=#0e1317
palette = 1=#a14a3a
palette = 2=#78bf78
palette = 3=#bab38c
palette = 4=#93b2c3
palette = 5=#cd98cd
palette = 6=#a8cccc
palette = 7=#f6cf9b

# Bright colors
palette = 8=#93a0ab
palette = 9=#ca6c5a
palette = 10=#b2deb2
palette = 11=#d9d5bd
palette = 12=#bfd3dd
palette = 13=#e3c0e3
palette = 14=#c8e0e0
palette = 15=#ffffff
