$color = rgba(14, 19, 23, 1)
$inner_color = rgba(14, 19, 23, 0.66)
$outer_color = rgba(230, 97, 0, 1)
$font_color = rgba(246, 207, 155, 1)
$placeholder_color = rgba(246, 207, 155, 0.7)
$check_color = rgba(168, 204, 204, 1)
