# Terminale su workspace 1 con fastfetch
exec-once = hyprctl dispatch workspace 1
exec-once = hyprctl dispatch exec "$TERMINAL -e bash -c 'fastfetch; exec bash'"

# Browser su workspace 2
exec-once = hyprctl dispatch workspace 2
exec-once = hyprctl dispatch exec "$browser"

